const words=[
['chest',[['💪','Human chest','кеуде'],['🧰','Storage chest','сандық']],[['My ___ hurts after running.','💪'],['The old ___ was full of toys.','🧸']]],
['head',[['🧑','A person’s head','бас'],['👩‍💼','A leader','басшы']],[['Put a hat on your ___.','🧢'],['She is the ___ of our school.','🏫']]],
['palm',[['✋','Palm of a hand','алақан'],['🌴','Palm tree','пальма']],[['The coin is in my ___.','🪙'],['A tall ___ grows by the beach.','🏖️']]],
['pupil',[['🧑‍🎓','A school pupil','оқушы'],['👁️','Pupil of an eye','көз қарашығы']],[['Every ___ has a new book.','📘'],['The ___ is the dark part of your eye.','👁️']]],
['bank',[['🏦','Money bank','банк'],['🏞️','River bank','өзен жағасы']],[['My mother works at a ___.','🏦'],['We sat on the river ___.','🌊']]],
['bark',[['🌳','Tree bark','ағаш қабығы'],['🐕','A dog’s bark','иттің үруі']],[['The tree has rough ___.','🌳'],['The dog can ___ loudly.','🐶']]],
['jam',[['🍓','Fruit jam','тосап'],['🚗','Traffic jam','кептеліс']],[['I put strawberry ___ on my toast.','🍞'],['We were late because of a traffic ___.','🚙']]],
['spring',[['🌷','The spring season','көктем'],['🌀','A metal spring','серіппе']],[['Flowers grow in ___.','🌷'],['There is a ___ inside this toy.','🧸']]],
['fan',[['🌀','Electric fan','желдеткіш'],['🙌','A sports fan','жанкүйер']],[['Turn on the ___, please.','☀️'],['I am a big football ___.','⚽']]],
['date',[['📅','Calendar date','күн, дата'],['🌴','Date fruit','құрма']],[['What is the ___ today?','📅'],['This sweet ___ grows on a palm tree.','🌴']]],
['fly',[['✈️','To fly','ұшу'],['🐝','A fly','шыбын']],[['Birds can ___ in the sky.','🐦'],['A ___ is sitting on the wall.','🐝']]],
['match',[['🔥','A match stick','сіріңке'],['🏟️','A sports match','спорттық матч']],[['Dad lit the fire with a ___.','🔥'],['We watched a football ___.','⚽']]],
['bat',[['🦇','A flying bat','жарқанат'],['🏏','A sports bat','спорттық таяқ']],[['A ___ flies at night.','🌙'],['He hit the ball with a ___.','⚾']]],
['well',[['😊','Feeling well','жақсы'],['🕳️','A water well','құдық']],[['I feel ___ today.','😊'],['They get water from the ___.','🪣']]]];
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)],matchTasks=words.flatMap((x,w)=>x[1].map((_,m)=>({w,m}))),contextTasks=words.flatMap((x,w)=>x[2].map((_,m)=>({w,m})));let st,ctx;
const ipa={chest:'/tʃest/',head:'/hed/',palm:'/pɑːm/',pupil:'/ˈpjuːpəl/',bank:'/bæŋk/',bark:'/bɑːk/',jam:'/dʒæm/',spring:'/sprɪŋ/',fan:'/fæn/',date:'/deɪt/',fly:'/flaɪ/',match:'/mætʃ/',bat:'/bæt/',well:'/wel/'};
function show(id,n=0){$$('.screen').forEach(x=>x.classList.toggle('active',x.id===id));$$('nav span').forEach(x=>x.classList.toggle('on',+x.dataset.stage===n));$('#homeBtn').classList.toggle('hidden',id==='home');scrollTo(0,0)}
function score(){ $('#score').textContent=st.score }
function speak(t){speechSynthesis.cancel();let u=new SpeechSynthesisUtterance(t);u.lang='en-US';u.rate=.78;speechSynthesis.speak(u)}
function tone(ok=true){try{ctx ||= new AudioContext();let o=ctx.createOscillator(),g=ctx.createGain();o.connect(g);g.connect(ctx.destination);o.frequency.value=ok?680:210;g.gain.setValueAtTime(.1,ctx.currentTime);g.gain.exponentialRampToValueAtTime(.001,ctx.currentTime+.25);o.start();o.stop(ctx.currentTime+.25)}catch{}}
function start(){st={player:$('#name').value.trim()||'Gamer Star',score:0,learn:0,opened:new Set(),match:0,context:0,first:true};score();show('learn',1);renderLearn()}
function renderLearn(){let x=words[st.learn];st.opened=new Set();$('#learnNo').textContent=st.learn+1;$('#learnProgress').style.width=st.learn/14*100+'%';$('#learnWord').textContent=x[0].toUpperCase();$('#learnNext').disabled=true;$('#learnNext').textContent=st.learn===13?'СӘЙКЕСТЕНДІРУДІ БАСТАУ ▶':'КЕЛЕСІ ▶';$('#learnFeedback').className='feedback';$('#learnFeedback').textContent='Екі суретті де бас';$('#learnMeanings').innerHTML=x[1].map((m,i)=>`<button data-meaning="${i}"><span>${m[0]}</span><b>Ашу үшін бас</b><em>Мағынасын көр</em><div><strong>${m[1]}</strong><small>${m[2]}</small></div></button>`).join('')}
function openMeaning(i){if(st.opened.has(i))return;st.opened.add(i);let b=$(`[data-meaning="${i}"]`);b.classList.add('revealed');speak(words[st.learn][1][i][1]);if(st.opened.size===2){st.score++;score();$('#learnNext').disabled=false;$('#learnFeedback').textContent='⭐ Екі мағына да ашылды! +1 ұпай';$('#learnFeedback').className='feedback good';tone()}}
function nextLearn(){if(st.learn<13){st.learn++;renderLearn()}else{show('matching',2);renderMatch()}}
function pair(t){let a=[[words[t.w][1][t.m],t.m],[words[t.w][1][1-t.m],1-t.m]];return Math.random()>.5?a:a.reverse()}
function renderMatch(){let t=matchTasks[st.match],x=words[t.w];st.first=true;$('#matchNo').textContent=st.match+1;$('#matchProgress').style.width=st.match/28*100+'%';$('#dragChip').dataset.mi=t.m;$('#dragChip').innerHTML=`<b>${x[0].toUpperCase()}</b><small>${x[1][t.m][2]}</small>`;$('#matchFeedback').textContent='';$('#matchFeedback').className='feedback';$('#dropPictures').innerHTML=pair(t).map(([m,i])=>`<button data-drop="${i}"><span>${m[0]}</span><b>${m[1]}</b></button>`).join('')}
function tryMatch(i){let t=matchTasks[st.match];if(+i===t.m){if(st.first){st.score++;score()}$('#matchFeedback').textContent='✅ Дұрыс! +1 ұпай';$('#matchFeedback').className='feedback good pop';tone();$$('[data-drop]').forEach(x=>x.disabled=true);setTimeout(()=>{st.match++;if(st.match<28)renderMatch();else{show('context',3);renderContext()}},650)}else{st.first=false;$('#matchFeedback').textContent='❌ Қайтадан байқап көр!';$('#matchFeedback').className='feedback bad shake';tone(false)}}
function options(wi){let a=[words[wi][0]];while(a.length<3){let w=words[Math.floor(Math.random()*14)][0];if(!a.includes(w))a.push(w)}return a.sort(()=>Math.random()-.5)}
function renderContext(){let t=contextTasks[st.context],x=words[t.w],s=x[2][t.m];st.first=true;$('#contextNo').textContent=st.context+1;$('#contextProgress').style.width=st.context/28*100+'%';$('#contextEmoji').textContent=s[1];$('#sentence').textContent=s[0];$('#options').innerHTML=options(t.w).map((w,i)=>`<button data-option="${w}"><span>${String.fromCharCode(65+i)}</span>${w.toUpperCase()}</button>`).join('');$('#contextFeedback').textContent='';$('#contextFeedback').className='feedback';$('#contextNext').classList.add('hidden')}
function answer(w){let t=contextTasks[st.context],correct=words[t.w][0];if(w===correct){if(st.first){st.score+=2;score()}$$('[data-option]').forEach(x=>{x.disabled=true;if(x.dataset.option===correct)x.classList.add('correct')});$('#contextFeedback').textContent=`✅ ${correct.toUpperCase()} — Дұрыс! +${st.first?2:0} ұпай`;$('#contextFeedback').className='feedback good pop';$('#contextNext').classList.remove('hidden');tone()}else{st.first=false;let b=$(`[data-option="${w}"]`);b.disabled=true;b.classList.add('wrong');$('#contextFeedback').textContent='❌ Қайтадан байқап көр!';$('#contextFeedback').className='feedback bad shake';tone(false)}}
function nextContext(){st.context++;st.context<28?renderContext():finish()}
function finish(){st.score=Math.min(100,st.score+2);score();$('#player').textContent=st.player;$('#finalScore').textContent=`${st.score} / 100`;$('#performance').textContent=st.score>=95?'🏆 WORD TWINS MASTER!':st.score>=80?'⭐ GREAT JOB!':st.score>=60?'👍 GOOD TRY!':'💪 KEEP PRACTISING!';show('finish',4);tone()}
$('#start').onclick=start;$('#again').onclick=start;$('#homeBtn').onclick=()=>show('home');$('#learnNext').onclick=nextLearn;$('#wordSound').onclick=()=>speak(words[st.learn][0]);$('#contextNext').onclick=nextContext;$('#sentenceSound').onclick=()=>{let t=contextTasks[st.context];speak(words[t.w][2][t.m][0].replace('___',words[t.w][0]))};document.addEventListener('click',e=>{let m=e.target.closest('[data-meaning]');if(m)openMeaning(+m.dataset.meaning);let d=e.target.closest('[data-drop]');if(d)tryMatch(d.dataset.drop);let o=e.target.closest('[data-option]');if(o)answer(o.dataset.option)});$('#dragChip').ondragstart=e=>e.dataTransfer.setData('text/plain',$('#dragChip').dataset.mi);$('#dropPictures').ondragover=e=>e.preventDefault();$('#dropPictures').ondrop=e=>{e.preventDefault();let d=e.target.closest('[data-drop]');if(d)tryMatch(d.dataset.drop)};$('#name').onkeydown=e=>{if(e.key==='Enter')start()};
const baseRenderLearn=renderLearn;renderLearn=function(){baseRenderLearn();$('#learnPronunciation').textContent=ipa[words[st.learn][0]]};
$('#dictionaryList').innerHTML=words.map(x=>`<article class="dictionary-row"><button data-say="${x[0]}" aria-label="${x[0]} сөзін тыңдау">🔊</button><div><b>${x[0].toUpperCase()}</b><span>${ipa[x[0]]}</span></div><p>${x[1][0][0]} ${x[1][0][2]} <i>•</i> ${x[1][1][0]} ${x[1][1][2]}</p></article>`).join('');
$('#dictionaryBtn').onclick=()=>$('#dictionary').showModal();$('#dictionaryClose').onclick=()=>$('#dictionary').close();$('#dictionary').onclick=e=>{if(e.target===$('#dictionary'))$('#dictionary').close()};document.addEventListener('click',e=>{let b=e.target.closest('[data-say]');if(b)speak(b.dataset.say)});
$('.home > div > small').textContent='АҒЫЛШЫН ТІЛІ ОЙЫНЫ';
$('#start').textContent='START GAME ▶';
$('#finish h2').textContent='🎉 CONGRATULATIONS!';
$('#finish article > small').textContent='YOUR SCORE';
$('#finish article > p:first-child').innerHTML='Player: <b id="player">Gamer Star</b>';
$('#finish article > p:last-child').innerHTML='You have studied <b>14 Word Twins!</b>';
$('#again').textContent='PLAY AGAIN 🔄';
$('.home article label').textContent='GAMER STAR';$('#name').value='Gamer Star';$('.home aside img').src='assets/word-twins-students.png';$('.home aside img').alt='A boy and a girl learning English';
let installPrompt;const installButton=$('#installApp');window.addEventListener('beforeinstallprompt',event=>{event.preventDefault();installPrompt=event;installButton.classList.remove('hidden')});installButton.onclick=async()=>{if(!installPrompt)return;installPrompt.prompt();await installPrompt.userChoice;installPrompt=null;installButton.classList.add('hidden')};window.addEventListener('appinstalled',()=>installButton.classList.add('hidden'));if('serviceWorker' in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('./service-worker.js'));
document.head.insertAdjacentHTML('beforeend','<style>.install-app{position:fixed;right:22px;bottom:22px;z-index:50;border:0;border-radius:16px;padding:14px 20px;color:#fff;background:linear-gradient(#865de3,#5832bb);box-shadow:0 6px #3d2288,0 12px 28px #24145855;font-weight:900;cursor:pointer}.install-app:hover{transform:translateY(-2px)}@media(max-width:520px){.install-app{right:12px;bottom:12px}}</style>');
